source 'http://rubygems.org'

gem 'rails', '3.2.9'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem  'thin'
gem  'pg'
gem   'rdoc'
gem 'devise', ">= 2.1.2"
gem 'foreman'
  

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '> 3.2'
  gem 'coffee-rails', '> 3.2'
  gem 'uglifier', '>= 1.0.3'
  gem 'execjs'
  gem 'therubyracer'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  gem "factory_girl_rails", "~> 1.2"
  gem "shoulda", ">= 0"
  # Pretty printed test output
  gem 'turn', :require => false
end

gem 'milia', :path => "../../../milia"
